import {
  app,
  BrowserWindow,
  Tray,
  Menu,
  nativeImage,
  ipcMain,
  Notification,
} from "electron";
import path from "node:path";
import {
  startFocus,
  startBreak,
  stopTimer,
  setTimerCallbacks,
  TimerState,
  setDurations,
} from "./timerlogic/timer";
import {
  getSettings,
  setSettings,
  saveSession,
  getWeeklySessions,
  getAllSessions,
  getSessionsByDay,
} from "./db/db";
import sound from "sound-play";

const getIconPath = (): string => {
  // it's a trick to make sure the icon is correctly loaded.
  if (app.isPackaged) {
    return path.join(process.resourcesPath, "icon.png");
  }
  return path.join(__dirname, "..", "..", "assets", "icon.png");
};

const getSoundPath = () => {
  // em produção os extraResource ficam em process.resourcesPath
  // em dev apontamos direto para a pasta assets do projeto
  return app.isPackaged
    ? path.join(process.resourcesPath, "notify.mp3")
    : path.join(app.getAppPath(), "assets", "notify.mp3");
};

const icon = nativeImage.createFromPath(getIconPath());

app.setAppUserModelId("com.magikzub.pomodoro");

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;

const createWindow = (): void => {
  const winIcon = nativeImage.createFromPath(getIconPath());

  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    icon: winIcon,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.setIcon(icon);

  // closed btn will only hide the window
  mainWindow.on("close", (event) => {
    if (!(app as any).isQuitting) {
      // quando ele clica no X isso aqui vem false
      event.preventDefault();
      mainWindow?.hide();
    }
  });

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

const formatTime = (seconds: number): string => {
  const min = Math.floor(seconds / 60)
    .toString()
    .padStart(2, "0");
  const sec = (seconds % 60).toString().padStart(2, "0");
  return `${min}:${sec}`;
};

const updateTrayTooltip = (state: TimerState, remaining: number) => {
  if (!tray) return;
  if (state === "idle") {
    tray.setToolTip("Pomodoro App");
    return;
  }
  const label = state === "focus" ? "Foco" : "Pausa";
  tray.setToolTip(`${label} - ${formatTime(remaining)}`);
};

const createTray = (): void => {
  tray = new Tray(icon);

  const contextMenu = Menu.buildFromTemplate([
    { label: "Abrir                     ", click: () => mainWindow?.show() },
    { type: "separator" },
    {
      label: "Sair",
      click: () => {
        (app as any).isQuitting = true; // realmente fecha o app
        app.quit();
      },
    },
    { label: "Iniciar foco (25min)", click: () => startFocus() },
    { label: "Iniciar pausa (5min)", click: () => startBreak() },
    { label: "Parar", click: () => stopTimer() },
    { type: "separator" },
    {
      label: "Sair",
      click: () => {
        (app as any).isQuitting = true;
        app.quit();
      },
    },
  ]);

  tray.setToolTip("Pomodoro App");
  tray.setContextMenu(contextMenu);
  tray.on("click", () => mainWindow?.show());
};

app.on("window-all-closed", () => {
  // não sair — app fica vivo na tray
});

app.on("ready", () => {
  createWindow();
  createTray();

  setTimerCallbacks({
    onTick: (state, remaining) => {
      updateTrayTooltip(state, remaining);
      mainWindow?.webContents.send("timer:tick", state, remaining);
    },
    onComplete: (state) => {
      updateTrayTooltip(state, 0);
      const duration =
        state === "focus"
          ? Number(getSettings("focus_duration")) * 60
          : Number(getSettings("break_duration")) * 60;
      if (state !== "idle") saveSession(state, duration, true);

      // notificação quando um ciclo completa
      const notify = new Notification({
        title: state === "focus" ? "Foco Finalizado!" : "Pausa finalizada!",
        body:
          state === "focus"
            ? "Hora de fazer uma pausa!"
            : "Vamos voltar ao trabalho!",
        icon: getIconPath(),
      });

      notify.show();
      sound.play(getSoundPath()).catch((err) => {
        console.error(err);
      });
    },
  });

  ipcMain.on("timer:start-focus", () => startFocus());
  ipcMain.on("timer:stop", () => stopTimer());
  ipcMain.on("timer:start-break", () => startBreak());

  // getting from the db
  const focus = Number(getSettings("focus_duration"));
  const breakMin = Number(getSettings("break_duration"));
  if (focus && breakMin) {
    setDurations(focus, breakMin);
  }

  // config
  ipcMain.handle("config:get-durations", () => {
    const focus = Number(getSettings("focus_duration")) || 25;
    const breakTimer = Number(getSettings("break_duration")) || 5;
    setDurations(focus, breakTimer);
    return { focus, break: breakTimer };
  });
  ipcMain.handle(
    "config:set-durations",
    (_event, focus: number, breakTimer: number) => {
      setSettings("focus_duration", focus.toString());
      setSettings("break_duration", breakTimer.toString());
      setDurations(focus, breakTimer);
    },
  );

  // sessions
  ipcMain.handle("sessions:weekly-sessions", () => getWeeklySessions());
  ipcMain.handle("sessions:get-all", () => getAllSessions());
  ipcMain.handle("sessions:get-all-by-day", (_event, day: string) =>
    getSessionsByDay(day),
  );
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
