import {
  app,
  BrowserWindow,
  Tray,
  Menu,
  NativeImage,
  nativeImage,
  ipcMain,
} from "electron";
import path from "node:path";
import {
  startFocus,
  startBreak,
  stopTimer,
  setTimerCallbacks,
  TimerState,
  setDurations,
  getDurations,
} from "./timerlogic/timer";

const iconPath = path.join(__dirname, "..", "..", "assets", "icon.ico");
const icon = nativeImage.createFromPath(iconPath);

app.setAppUserModelId("com.magikzub.pomodoro");

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;
let tray: Tray | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    icon: path.join(__dirname, "..", "..", "assets", "icon.ico"),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // closed btn will only hide the window
  mainWindow.on("close", (event) => {
    if (!(app as any).isQuitting) {
      // quando ele clica no X isso aqui vem false
      event.preventDefault();
      mainWindow?.hide();
    }
  });

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

const formatTime = (seconds: number): string => {
  const min = Math.floor(seconds / 60)
    .toString()
    .padStart(2, "0");
  const sec = (seconds % 60).toString().padStart(2, "0");
  return `${min}:${sec}`;
};

const updateTrayTooltip = (state: TimerState, remaining: number) => {
  if (!tray) return;
  if (state === "idle") {
    tray.setToolTip("Pomodoro App");
    return;
  }
  const label = state === "focus" ? "Foco" : "Pausa";
  tray.setToolTip(`${label} - ${formatTime(remaining)}`);
};

const createTray = (): void => {
  tray = new Tray(icon);

  const contextMenu = Menu.buildFromTemplate([
    { label: "Abrir                     ", click: () => mainWindow?.show() },
    { type: "separator" },
    {
      label: "Sair",
      click: () => {
        (app as any).isQuitting = true; // realmente fecha o app
        app.quit();
      },
    },
    { label: "Iniciar foco (25min)", click: () => startFocus() },
    { label: "Iniciar pausa (5min)", click: () => startBreak() },
    { label: "Parar", click: () => stopTimer() },
    { type: "separator" },
    {
      label: "Sair",
      click: () => {
        (app as any).isQuitting = true;
        app.quit();
      },
    },
  ]);

  tray.setToolTip("Pomodoro App");
  tray.setContextMenu(contextMenu);
  tray.on("click", () => mainWindow?.show());
};

app.on("window-all-closed", () => {
  // não sair — app fica vivo na tray
});

app.on("ready", () => {
  createWindow();
  createTray();

  setTimerCallbacks({
    onTick: (state, remaining) => {
      updateTrayTooltip(state, remaining);
      mainWindow?.webContents.send("timer:tick", state, remaining);
    },
    onComplete: (state) => updateTrayTooltip(state, 0),
  });

  ipcMain.on("timer:start-focus", () => startFocus());
  ipcMain.on("timer:stop", () => stopTimer());
  ipcMain.on("timer:start-break", () => startBreak());
  ipcMain.handle(
    "timer:set-durations",
    (_event, focus: number, breakTimer: number) =>
      setDurations(focus, breakTimer),
  );
  ipcMain.handle("timer:get-durations", () => getDurations());
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
